title: "Kuy, UCR! 🇺🇸📚"
description: "Panduan operasional lengkap: Short Course PKUMI-LPDP di UC Riverside, California (28 Sep – 25 Des 2026)"
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: false
titles_from_headings:
  enabled: true
show_downloads: false
